config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :user
  

  root 'landings#index'
  
  resources :news_items do
    put 'like', to: 'news_items#like'
    put 'dislike', to: 'news_items#dislike'
  end
  
  resources :news_sources
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  acts_as_votable 
  
  belongs_to :news_source
end

app/models/news_source.rb
class NewsSource < ActiveRecord::Base
  acts_as_votable 
  
  #https://www.wired.com/feed/
end

app/models/user.rb
class User < ActiveRecord::Base
    acts_as_voter
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
require 'nokogiri'

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?, except: [:sign_up, :sign_in]
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
    
  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(new_user_session_path)
        fallback_redirect = new_user_session_path
      else
        fallback_redirect = "/sign_in"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/landings_controller.rb
require 'open-uri'

class LandingsController < ApplicationController
  before_action :require_user_signed_in
  def index
    @news_items = NewsItem.all.order(:pubdate)
  end
  
  
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
    before_action :require_user_signed_in
    before_action :set_news_item, only: [:like, :dislike]
    
    def like
        respond_to do |format|
          if current_user.likes @news_item    
              format.json { render json: {id: @news_item.id, count: @news_item.get_likes.size}}
          else
              format.json { render json: root_path.errors, status: :unprocessable_entity }
          end
        end
    end

    def dislike
      respond_to do |format|
          if current_user.dislikes @news_item
              format.json { render json: {id: @news_item.id, count: @news_item.get_likes.size}}
          else
              format.json { render json: root_path.errors, status: :unprocessable_entity }
          end
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_news_item
        @news_item = NewsItem.find(params[:news_item_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_item_params
        params.require(:news_item).permit(:news_item_id)
    end
end

app/controllers/news_sources_controller.rb
class NewsSourcesController < ApplicationController
  before_action :require_user_signed_in
  include NewsItemsHelper
  
  before_action :set_news_source, only: [:show, :edit, :update, :destroy]

  # GET /news_sources
  # GET /news_sources.json
  def index
    @news_sources = NewsSource.all
  end

  # GET /news_sources/1
  # GET /news_sources/1.json
  def show
  end

  # GET /news_sources/new
  def new
    @news_source = NewsSource.new
  end

  # GET /news_sources/1/edit
  def edit
  end

  # POST /news_sources
  # POST /news_sources.json
  def create
    @news_source = NewsSource.new(news_source_params)

    respond_to do |format|
      if @news_source.save
        populate_feed
        format.html { redirect_to @news_source, notice: 'News source was successfully created.' }
        format.json { render :show, status: :created, location: @news_source }
      else
        format.html { render :new }
        format.json { render json: @news_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_sources/1
  # PATCH/PUT /news_sources/1.json
  def update
    respond_to do |format|
      if @news_source.update(news_source_params)
        populate_feed
        format.html { redirect_to @news_source, notice: 'News source was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_source }
      else
        format.html { render :edit }
        format.json { render json: @news_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_sources/1
  # DELETE /news_sources/1.json
  def destroy
    @news_source.destroy
    respond_to do |format|
      populate_feed
      format.html { redirect_to news_sources_url, notice: 'News source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_source
      @news_source = NewsSource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_source_params
      params.require(:news_source).permit(:name, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
  
  
end

app/helpers/news_items_helper.rb
module NewsItemsHelper
    mattr_accessor :doc

    def get_img_src(item, default_img = nil)
        # init empty src
        img_src = default_img

        # check description for images
        if item.key?('description')
            img_tag = get_img_tag(item['description'])
            return img_tag['src'].to_s unless img_tag.nil?
        end

        # check for thumbnail
        if img_src == default_img
            img_src = item['thumbnail']['url'] if item.key?('thumbnail')
        end

        # check for enclosure
        if img_src == default_img
            img_src = item['enclosure']['url'] if item.key?('enclosure')
        end
        
        # check for enclosure
        if img_src == default_img
            img_src = item['content']['url'] if item.key?('content')
        end

        # return whatever source was found
        img_src
    end

    def get_default_img(_item)
        default_img = 'placeholder_tech.jpeg'
    end

    def get_img_tag(string)
        string = string[0] if string.is_a?(Array)
        doc = Nokogiri::HTML(string)
        doc.css('img').first
    end

    def display_array(s)
        return s.join(', ') if s.is_a?(Array)
        s
    end

    def populate_feed
        NewsItem.destroy_all
        sources = NewsSource.all
        sources.each do |source|
            xml = Nokogiri::XML(open(source.url))
            xml_hash = Hash.from_xml(xml.to_s)

            coder = HTMLEntities.new
            channel = xml_hash['rss']['channel']

            channel['item'].each do |item|
                # set default values
                default_img = get_default_img(item)
                title = item['title']
                description = item['description'].is_a?(Array) ? item['description'][0] : item['description']
                link = item['link']
                categories = item['category']
                pubDate = item['pubDate']

                NewsItem.create!(title: title, description: coder.decode(description), link: link, image: get_img_src(item, default_img), categories: display_array(categories), pubdate: pubDate, news_source_id: source.id)
            end
        end
  end
end

app/helpers/news_sources_helper.rb
module NewsSourcesHelper
end

app/views/elements/_article.html.erb
<% if !article.nil? %>


<article>
    <legend class="source-title"><%= article.news_source.name %></legend>
    
    <%= render 'elements/like_area', article: article %>
    
    <a target='_blank' href="<%= article.link %>" class="image">
        <div class="background-img" style="background-image: url('<%= article.image =~ URI::regexp ? article.image : '/assets/'+article.image%>') "></div>
    </a>
    <h3 class="article-title"><%= article.title %></h3>
    <p class="article-categories">Categories: <%= article.categories %></p>
    <p class="article-description"><%= sanitize article.description, tags: %w(strong em a), attributes: %w(href) %></p>
    <ul class="actions">
        <li>
            <a href="<%= article.link %>" target='_blank' class="button">More</a>
        </li>
    </ul>
</article>
<% end %>

app/views/elements/_banner.html.erb
<% item ||= NewsItem.first %>
<section id="banner">
  <div class="content">
    <legend class="source-title"><%= item.news_source.name %></legend>
    <%= render 'elements/like_area', article: item %>
    <header>
      <h2><%= item.title %></h2>
      <p><%= item.categories %></p>
    </header>
    <p><%= strip_tags item.description %></p>
    <ul class="actions">
      <li><a href="#" class="button big">Learn More</a></li>
    </ul>
  </div>
  <span class="image object">
    <%= image_tag item.image %>
  </span>
</section>

app/views/elements/_footer.html.erb
<!-- Footer -->
<footer id="footer">
    <p class="copyright">&copy; Untitled. All rights reserved. Demo Images:
        <a href="https://unsplash.com">Unsplash</a>. Design:
        <a href="https://html5up.net">HTML5 UP</a>.</p>
</footer>

app/views/elements/_header.html.erb
<!-- Header -->
  <header id="header">
    <span class="logo"><a href="<%= root_path %>"><strong>ScapesNews</strong></a> by <a href="http://github.com/scaperoth">Scaperoth</a></span>
    <ul class="icons">
      <% if user_signed_in? %>
      <li>
        <%= link_to "", destroy_user_session_path, class: "icon fa-sign-out", method: :delete%>
      </li>
      <li>
        <%= link_to "", edit_user_registration_path, class: "icon fa-user" %>
      </li>
      <% else %>
        <%= link_to "", new_user_session_path, class: "icon fa-sign-in" %>
      <% end %> 
    </ul>
  </header>
  <legend><small>theme by <a href="https://html5up.net/editorial">HTML5 UP</a></small></legend>

app/views/elements/_like_area.html.erb
<% if !article.nil? %>

<% liked_article = current_user.voted_up_on?(article) %>
<% like_icon = 'heart' %>
<% dislike_icon = 'heart-o' %>
<% link = liked_article ? news_item_dislike_path(article) : news_item_like_path(article) %>
<% toggle_link = liked_article ? news_item_like_path(article) : news_item_dislike_path(article) %>
<% icon = liked_article ? like_icon : dislike_icon %>
<% toggle_icon = liked_article ? dislike_icon : like_icon %>

<div class="like-area">
    <%= link_to ('<i class="fa fa-'+icon+'"></i>').html_safe, link, method: :put, remote: true, class: 'like-btn', data: {toggle_icon: toggle_icon, icon: icon, toggle_href: toggle_link, id: 'like-news-item-'+article.id.to_s} %>

    <p class="likes-count" data-id="likes-count-<%= article.id.to_s %>"><%= article.get_likes.size %></p>
</div>

<% end %>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/elements/_sidebar.html.erb
<!-- Sidebar -->
  <div id="sidebar">
    <div class="inner">

      <!-- Search -->
        <section id="search" class="alt">
          <form method="post" action="#">
            <input type="text" name="query" id="query" placeholder="Search" />
          </form>
        </section>

      <!-- Menu -->
        <nav id="menu">
          <header class="major">
            <h2>Menu</h2>
          </header>
          <ul>
            <li><a href="<%= root_path %>">Homepage</a></li>
            <li><a href="<%= news_sources_path %>">News Sources</a></li>
          </ul>
        </nav>
        
        <!-- Section -->
          <section>
            <header class="major">
              <h2>Account</h2>
            </header>
            <li style="list-style:none;"><a href="<%= edit_user_registration_path %>">Edit My Account</a></li>
          </section>


      <!-- Section -->
        <section>
          <header class="major">
            <h2>Get in touch</h2>
          </header>
          <ul class="contact">
            <li class="fa-envelope-o"><a href="#">matt@scaperoth.com</a></li>
          </ul>
        </section>

        
        <%= render partial: "elements/footer" %>

    </div>
  </div>

app/views/landings/index.html.erb
<!-- Banner -->
<%= 
# create the banner using only the first 
# feed item from the model 
render 'elements/banner', item: @news_items.first 
%>

<!-- Section -->
<section>
  <header class="major">
    <h2>Ipsum sed dolor</h2>
  </header>
  <div class="posts">
    
    <% 
    # loop through all but the 
    # first element and create an 
    # article out of each feed item 
    @news_items.all[1..-1].each do |news_item| 
    %>
      <%= render 'elements/article', article: news_item %>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>ScapesNews</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
        <!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->

        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1"/></head>
    <body>

        <!-- Wrapper -->
        <div id="wrapper">

            <!-- Main -->
            <div id="main">
                <div class="inner">

                    <%= render partial: "elements/header" %>
                </br>
                <%= yield %>
            </div>
        </div>

        <% if user_signed_in? %>
        <%= render partial: "elements/sidebar" %>
        <% end %>
    </div>
</body>
</html>

app/views/news_sources/_form.html.erb
<%= simple_form_for(@news_source) do |f| %>
<%= f.error_notification %>
<div class="form-inputs">
    <div class="6u 12u$(xsmall)">
        <%= f.input :name %>
    </div>

    <div class="6u 12u$(xsmall)">
        <%= f.input :url %>
    </div>
</div>

<div class="form-actions">
    <%= f.button :submit %>
</div>
<% end %>

app/views/news_sources/edit.html.erb
<h2>Editing <%= @news_source.name %> News Source</h2>

<%= render 'form' %>

<%= link_to 'Show', @news_source %> |
<%= link_to 'Back', news_sources_path %>

app/views/news_sources/index.html.erb
<h1>News Sources</h1>

<table>
  <thead>
    <tr>
      <th colspan="1"></th>
      <th colspan="1"></th>
      <th colspan="1"></th>
      <th colspan="1"></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @news_sources.each do |news_source| %>
      <tr>
        <td><%= news_source.name %></td>
        <td><%= news_source.url %></td>
        <td><%= link_to 'Show', news_source %></td>
        <td><%= link_to 'Edit', edit_news_source_path(news_source) %></td>
        <td><%= link_to 'Destroy', news_source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News source', new_news_source_path %>

app/views/news_sources/new.html.erb
<h1>New News Source</h1>

<%= render 'form' %>

<%= link_to 'Back', news_sources_path %>

app/views/news_sources/show.html.erb
<%= bootstrap_flash %>

<p>Name: <%= @news_source.name %> </p>
<p>URL: <%= @news_source.url %> </p>

<%= link_to 'Edit', edit_news_source_path(@news_source) %> |
<%= link_to 'Back', news_sources_path %>

app/views/user/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>